### ISSUE TITLE
Adicionar programação do evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-site#13]
### Descrição
Atualizar o site com a programação do evento

### Requisitos para a atividade ser considerada como concluída

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/). Válido para atividades que dependem de imagem, como criação de artes e modificação do site.
- Programação postada no site

**Comment by alynnefs** [comment]
Até o momento a programação do Job Fair está assim. MELI e CornerShop ainda estão em processo de assinatura de contrato

![image](https://user-images.githubusercontent.com/17454743/134715443-84fc51ce-f3cd-4438-b982-6ba5c52ff3b6.png)

**Comment by alynnefs** [comment]
Mesas Redondas:
Segunda: AfroPython
Terça: APyB
Quarta: Dados Abertos

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/135933301-6c1e9536-5b35-4777-b698-aa4f2567d27b.png)

#476088 (azul escuro)
#ffc562 (amarelo)
#ff6d74 (rosa)
#4fddc3 (verde)
#61a8e8 (azul)
