### ISSUE TITLE
Adicionar informação dos patrocinadores

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-site#14]
### Descrição
Atualizar o site com informações das empresas patrocinadoras

### Requisitos para a atividade ser considerada como concluída

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/). Válido para atividades que dependem de imagem, como criação de artes e modificação do site.
- Patrocinadores adicionados com suas respectivas artes

**Comment by cecivieira** [comment]
@paulohenriquedsgn como ficou a parceria com Todas as Letras?
Fizeram a divulgação? Enviaram a logo para colocar no site?

**Comment by cecivieira** [comment]
@deboraazevedo essa é a issue que comentei. Estamos aguardando resposta da Comunicação

**Comment by deboraazevedo** [comment]
entrei em contato com o @paulohenriquedsgn pra ver se temos retorno disso

**Comment by paulohenriquedsgn** [comment]
> @paulohenriquedsgn como ficou a parceria com Todas as Letras?
> Fizeram a divulgação? Enviaram a logo para colocar no site?

@cecivieira eu creio que ficamos de colocar eles como apoiadores no nosso site para que eles pudessem iniciar a divulgação.

**Comment by cecivieira** [comment]
@paulohenriquedsgn tu poderia colocar a logo dentro do Drive e compartilhar o link aqui, por favor?

**Comment by cecivieira** [comment]
@muriloviana pra eu consegui te atribui essa issue, comenta aqui

**Comment by muriloviana** [comment]
> @muriloviana pra eu consegui te atribui essa issue, comenta aqui

Opa, vou dar prioridade nessa issue pra gente começar a mostrar as empresas no site! Já temos as infos que adicionaremos para cada empresa patrocinadora?

**Comment by cecivieira** [comment]
@muriloviana temos apenas informações essas duas empresas:
![image](https://user-images.githubusercontent.com/30605862/132887587-455466dc-c4d1-4c23-912a-7c10b65a7abe.png)
![image](https://user-images.githubusercontent.com/30605862/132887618-04d4ba37-c41e-48fc-89f7-2e8e61f3cf3c.png)
![image](https://user-images.githubusercontent.com/30605862/132887637-6715a820-8d06-41fc-b697-dca19ecf0808.png)

**Comment by cecivieira** [comment]
https://www.buser.com.br/
https://www.jusbrasil.com.br/
