### ISSUE TITLE
Alterar imagens

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-site#16]
Substituir algumas imagens do site para ter maior diversidade de gênero e raça.
Imagens utilizadas recentemente nos posts das redes sociais:
https://drive.google.com/file/d/1ih4lPH1QmrHFUU-57mYuSIwsMROjzxtY/view?usp=sharing

**Comment by muriloviana** [comment]
Olá, fiquei com uma dúvida. Quais imagens especificamente precisamos alterar e onde cada uma delas entraria?

**Comment by cecivieira** [comment]
@muriloviana Minha sugestão é que sejam substituídas as seguintes imagens:
![image](https://user-images.githubusercontent.com/30605862/132254117-f70bdcd0-c357-4f2d-9a12-b5acc5cbd032.png)
![image](https://user-images.githubusercontent.com/30605862/132254126-75b46ad3-12ef-4986-99ac-320098acb18a.png)

Por outras que possam refletir gênero fluido ou personagem sem gênero definido.

Não entendi a pergunta "onde cada uma delas entraria". Você poderia detalhá-la?

**Comment by muriloviana** [comment]
Massa! Minha dúvida era mais no sentido: a imagem "quatro pessoas codando simultaneamente" sai para a entrada da imagem "quatro pessoas, uma com uma mala de rodinhas, outra com uma planta de obras, outra com uma xícara e outra com um laptop" presente no svg.

Portanto, se já tivermos definido quais imagens entrarão no lugar dessas duas que você comentou, seria bem-vindo \o/
