### ISSUE TITLE
Sugestão: remover a última seção da home page antes do rodapé

### ISSUE THREAD

**Issue by muriloviana** [pythonbrasil/pybr2021-site#20]
Atualmente temos no site do evento, uma seção exclusiva para informar que a Python Brasil é a maior conferência da linguagem na América Latina. Acho essa informação relevante, porém, acredito que está ocupando uma fatia grande do site.

![Screen Shot 2021-09-07 at 17 57 22](https://user-images.githubusercontent.com/6524275/132409898-4fdd846e-ecea-4096-8947-7a7b712acdc4.png)

Minha sugestão é que possamos remover essa seção e incorporá-la em outra parte do site. Seja na seção "Sobre o evento PyBR", ou até mesmo na seção "Recursos".

Apenas enfatizando que esta é apenas uma sugestão, e pode ser tranquilamente descartada 😅

**Comment by cecivieira** [comment]
Concordo. Principalmente porque essa afirmação não é baseada em análise comparativa de dados (até onde eu sei); estamos só jogando para o universo.

@alynnefs o que você acha?

**Comment by alynnefs** [comment]
@muriloviana e @cecivieira, por mim podem mudar sim

**Comment by muriloviana** [comment]
Maravilha, farei essa alteração entre hoje e amanhã \o/
