### ISSUE TITLE
Adicionar nova página sobre doações

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-site#30]
Adicinar um novo html doações que deve ser linkado em um saiba mais na compra do ingresso e no menu inicial

Página será utilizada para informações constanstes abertas sobre as doações

https://github.com/pythonbrasil/pybr2021-org/issues/254

**Comment by gabubellon** [comment]
cc @muriloviana

**Comment by muriloviana** [comment]
Massa, acho super válido ter essas informações e transparência no site. @gabubellon quando tu fala "informações constantes abertas sobre as doações" seria o que exatamente? Só pra gente começar a ter uma ideia de como seria essa página.
