### ISSUE TITLE
Inserir Carta nas Patrocinadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-site#31]
![image](https://user-images.githubusercontent.com/30605862/134397770-df3cd1c0-3273-4dce-8259-6d0f17e84a38.png)

Descrição curta:
Carta é uma plataforma de software que permite que fundadores, investidores e funcionários gerenciem equity e ownership. Ao tornar a emissão de ações para os funcionários tão fácil quanto colocá-los na folha de pagamento, a Carta está criando mais owners e diminuindo o gap de ownership.

Descrição longa:
Carta é uma plataforma de software que permite que fundadores, investidores e funcionários gerenciem equity e ownership. Ao tornar a emissão de ações para os funcionários tão fácil quanto colocá-los na folha de pagamento, a Carta está criando mais owners e diminuindo o gap de ownership.
Desde sua fundação em 2012, a Carta cresce e administra centenas de bilhões de dólares em equity. 
Empresas como Canva, Classpass, Intercom e Union Square Ventures confiam na Carta para gerenciar seus cap tables, valuations, portfólio de investimentos e planos de equity. A Carta tem a confiança de mais de 21.000 empresas e mais de meio milhão de funcionários ao redor do mundo. 
A empresa está na lista da Forbes de melhores empresas SaaS do mundo, na lista da Fast Company de mais inovadoras e na list da Inc. de empresas privadas que mais crescem.

Link:
https://carta.com/

**Comment by cecivieira** [comment]
@muriloviana

**Comment by muriloviana** [comment]
Maravilha! @cecivieira tira uma dúvida, essa patrocinadora é ouro ou prata?

**Comment by alynnefs** [comment]
@muriloviana é ouro
