### ISSUE TITLE
Inserir AmbevTech nas Patrocinadoras

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-site#32]
Ainda sem dados, atualizo quando tiver.
AmbevTech é patrocinadora bronze.

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/134521107-aa57c625-01dc-48cf-9c0b-3f6fe207909a.png)

Descrição curta:
Somos a Ambev Tech - e ninguém une tecnologia e cerveja como a gente! Há 30 anos, temos a missão de transformar o dia a dia da maior cervejaria do planeta. Todos os dias, impactamos milhares de pessoas para fazer a bebida chegar do campo ao copo. Cada brinde tem um pouquinho de nós. 

Descrição longa:
A Ambev sempre foi conhecida por sua expertise na produção e distribuição e bebidas, mas desde 2018, a empresa vem promovendo sua jornada de transformação tecnológica com objetivo de atender as demandas dos consumidores e clientes da melhor forma, prevendo as suas necessidades para antecipar soluções. 
 
Com isso, em 2020, consolidou-se a criação da Ambev Tech, hub de inovação e tecnologia. A nova área representa a cultura de uma empresa tech, focada no core tecnológico, mas com todo o background, a cultura e o footprint Ambev. Atualmente, o hub conta com escritórios em Blumenau (SC), Maringá (PR), São Paulo (SP), Sorocaba (SP), Jaguariúna (SP) e Campinas (SP), além de profissionais de todo o país em modalidade remota. Desde sua criação, a Ambev Tech saltou de 450 para 1.800 colaboradores. 

Link:
www.ambevtech.com.br.

**Comment by cecivieira** [comment]
@muriloviana
