### ISSUE TITLE
Adicionar horários de sprints

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-site#40]
Assim que o horário estiver fechado, precisamos adicionar os horários das sprints

**Comment by alynnefs** [comment]
@muriloviana as últimas 3 issues são bem parecidas. Vamos conversar sobre como você pensa em fazer pra eu poder ajudar nisso? Queria só ver a estrutura pra ficar bonitinho, mas de resto consigo ajudar

**Comment by alynnefs** [comment]
@muriloviana são na programação, mas a duração é diferente. Aí não sei como seria pra organizar, porque tem palestra de 15:00 às 15:40 e o slot do job fair é de 15:00 às 16:30 (só um exemplo)

**Comment by muriloviana** [comment]
@alynnefs sua dúvida é super pertinente e muito bem levantada!

Meu ponto é que se centralizarmos fica mais fácil das pessoas participantes entenderem. Dito isso, estou à disposição, se codar for preciso, para colocar tudo junto no calendaryo.

**Comment by alynnefs** [comment]
@muriloviana okayy, organiza como achar que fica melhor 😊
Eu só não consegui visualizar, mas confio kkkkk
