### ISSUE TITLE
A Call for papers está aberta, mas não tem link nem aviso disso na landing page

### ISSUE THREAD

**Issue by jsbueno** [pythonbrasil/pybr2021-site#5]
Oi pessoal - se alguém procura a conferencia pelo google, cai na landing page - e lá parece que não tem _nada_ ainda, sendo que dentre as muitas coisas feitas, está a call for papers.

eu mesmo só achei a call for papers por que passei por um tweet com a chamada - acho importante colocar um link nessa landing page.

(estou só relatando a issue agora - se quiserem posso mandar um pr mais tarde)

**Comment by jsbueno** [comment]
![pybr2021tweets](https://user-images.githubusercontent.com/535236/125849749-b82179fa-22d3-42b6-b9e8-94fd025eab30.png)
(e pelo jeito não sou só eu quem está meio perdido)

**Comment by alynnefs** [comment]
a versão completa do site já está pra sair (:

**Comment by alynnefs** [comment]
@jsbueno eu tava na correria quando respondi, desculpa. Se você tiver tempo e quiser colocar o link não tem problema, só que próxima semana já deve ser substituído pelo site completo

**Comment by alynnefs** [comment]
vou fechar essa issue por ter sido feita no pull request #4 (:
